name: govanalysis

channels:
  - defaults

dependencies:
  - python=3.6.13

  - jupyter=1.0.0
  - pandas=1.1.5
  - matplotlib=3.3.4
  - seaborn=0.11.2
  - scikit-learn=0.24.2
  - requests=2.27.1

  - pip=21.2.2
